export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";

export const GET_ALL_REPORTS = 'GET_ALL_REPORTS';
export const SET_ALL_REPORTS = 'SET_ALL_REPORTS';
export const SET_FAVORITES = 'SET_FAVORITES';
export const SET_READ_LATER_REPORTS = 'SET_READ_LATER_REPORTS';
export const ADD_FAVORITE_REPORT = 'ADD_FAVORITE_REPORT';
export const ADD_READ_LATER_REPORT = 'ADD_READ_LATER_REPORT';
export const REMOVE_FAVORITE_REPORT = 'REMOVE_FAVORITE_REPORT';
export const REMOVE_READ_LATER_REPORT = 'REMOVE_READ_LATER_REPORT';

export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS';
export const SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS';

export const GET_PLANS = 'GET_PLANS';
export const SET_PLANS = 'SET_PLANS';

export const GET_SUPPORT_THREADS = 'GET_SUPPORT_THREADS';
export const SET_SUPPORT_THREADS = 'SET_SUPPORT_THREADS';
export const SET_SUPPORT_THREAD_MESSAGES = 'SET_SUPPORT_THREAD_MESSAGES';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const SET_DIVITION = 'SET_DIVITION';
export const SET_CATEGORY = 'SET_CATEGORY';